name: My_Githab_Actions

on:
  push:
    branches: "master"

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: print_hello_world
        run: echo "Hello World from hello job"
       
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
